name: publish

on:
  release:
    types: [released]
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') && startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}